[package]
name = "demo-customer-stub"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "demo_customer_stub"

[dependencies]
anchor-lang = "0.31.1"

[features]
no-entrypoint = []
idl-build = ["anchor-lang/idl-build"]
